In [1]:
import torch
from pathlib import Path

In [2]:
checkpoint_dir = Path(r"logs\Bios_both\both_adv\models")

In [3]:
_epoch_results = torch.load(checkpoint_dir / "checkpoint_epoch18.pth.tar")

In [4]:
_epoch_results.keys()

dict_keys(['epoch', 'epochs_since_improvement', 'loss', 'dev_predictions', 'test_predictions', 'dev_evaluations', 'test_evaluations'])

In [5]:
_epoch_results["dev_evaluations"]

{'rms_TPR': 0.43560272485196483,
 'accuracy': 0.8031215772179627,
 'macro_fscore': 0.7283969094156552,
 'micro_fscore': 0.8031215772179627}

In [6]:
# Load Bios dataset
import pandas as pd

data_dir = Path(r"D:\Project\Minding_Imbalance_in_Discriminator_Training\data\bios")

bios_dev_df = pd.read_pickle(data_dir / "bios_dev_df.pkl")
bios_test_df = pd.read_pickle(data_dir / "bios_test_df.pkl")

In [7]:
def return_y_g(my_df):
    my_df = my_df[my_df["economy_label"]!="Unknown"]
    return my_df["profession_class"].to_numpy(), my_df["intersection_class"].to_numpy()

In [8]:
dev_y, dev_g = return_y_g(bios_dev_df)
test_y, test_g = return_y_g(bios_test_df)

In [11]:
from src.evaluator import gap_eval_scores

In [12]:
gap_eval_scores(
    y_pred = _epoch_results["dev_predictions"], 
    y_true = dev_y, 
    protected_attribute = dev_g)

{'accuracy': 0.8031215772179627,
 'macro_fscore': 0.7283969094156552,
 'micro_fscore': 0.8031215772179627,
 'TPR_GAP': 0.43560272485196483,
 'FPR_GAP': 0.005944258843174327,
 'PPR_GAP': 0.039407736760176205}

In [13]:
gap_eval_scores(
    y_pred = _epoch_results["test_predictions"], 
    y_true = test_y, 
    protected_attribute = test_g)

{'accuracy': 0.8068291982334566,
 'macro_fscore': 0.7401184913339307,
 'micro_fscore': 0.8068291982334566,
 'TPR_GAP': 0.4340048368332264,
 'FPR_GAP': 0.006683039984137971,
 'PPR_GAP': 0.04327407716322931}

In [1]:
import torch

In [6]:
torch.cat([torch.rand((3,2)), torch.rand((4,2))], dim=0)

tensor([[0.3813, 0.4044],
        [0.5354, 0.5314],
        [0.2815, 0.2595],
        [0.1855, 0.4117],
        [0.6113, 0.1589],
        [0.0065, 0.0567],
        [0.2697, 0.1700]])

In [7]:
items = [0,1,2,3,4,5,6,7,8]

lb_dict = {
    (1,item):i for i, item in enumerate(items)
}

In [8]:
lb_dict

{(1, 0): 0,
 (1, 1): 1,
 (1, 2): 2,
 (1, 3): 3,
 (1, 4): 4,
 (1, 5): 5,
 (1, 6): 6,
 (1, 7): 7,
 (1, 8): 8}

In [10]:
[lb_dict[(1, item)]+=1 for item in items]

lb_dict

SyntaxError: invalid syntax (Temp/ipykernel_27468/1820016294.py, line 1)

In [13]:
import numpy as np
np.array([1,2,3]).shape

(3,)

In [17]:
tt = torch.tensor(
    [
        [
        [1,2,3],
        [4,5,6]
    ]]
)

In [18]:
tt

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [19]:
tt.squeeze()

tensor([[1, 2, 3],
        [4, 5, 6]])